all:
  hosts:
    local:
      ansible_host: 127.0.0.1
      ansible_connection: local
      ansible_become_method: su
      ansible_become_user: '{{ mac_admin_user }}'
      ansible_become_pass: '{{ mac_admin_pass }}'
