all:
  hosts:
    local:
      ansible_host: 127.0.0.1
      ansible_connection: local
      ansible_become_method: sudo
      ansible_become_user: '{{ ansible_become_user }}'
      ansible_become_pass: '{{ ansible_become_pass }}'
