---
- name: Set up local development environment
  hosts: local
  vars_files:
    - secrets.yml
  roles:
    # Tag each role so that we can select individual roles to run with ansible-playbook --tags
    - {role: package_manager, tags: ['package_manager', 'bootstrap']}
    - {role: cmdline, tags: ['cmdline']}
    - {role: git, tags: ['git']}
    - {role: lynx, tags: ['lynx']}
    - {role: imgcat, tags: ['imgcat']}
    - {role: ruby, tags: ['ruby']}
    - {role: nvim, tags: ['nvim']}
    # - {role: node, tags: ['node']}
    # Github Client
    # - {role: hub, tags: ['hub']}
    # https://direnv.net/
    # - {role: direnv, tags: ['direnv']}
    # - {role: tmux, tags: ['tmux']}
    # Cmdline Journal - https://jrnl.sh/en/stable/
    # - {role: jrnl, tags: ['jrnl']}
    # - {role: macos, tags: ['macos'], when: ansible_os_family == "Darwin"}
