---
- name: Set up local development environment
  hosts: local
  vars_files:
    - secrets.yml
  roles:
    - {role: package_manager, tags: ['package_manager']}
    - {role: cmdline, tags: ['cmdline']}
    - {role: ssh, tags: ['ssh']}
    - {role: ruby, tags: ['ruby']}
    # - {role: nvim, tags: ['nvim']}
    # - {role: node, tags: ['node']}
    - {role: vscodium, tags: ['vscodium']}
    - {role: macos, tags: ['macos'], when: ansible_os_family == "Darwin"}
    - {role: development, tags: ['development']}
    - {role: desktop, tags: ['desktop']}
    - {role: docker, tags: ['docker']}
