---
- name: Set up local development environment
  hosts: local
  vars_files:
    - secrets.yml
  roles:
    - {role: package_manager, tags: ['package_manager']}
    - {role: casks, tags: ['casks']}
    - {role: cmdline, tags: ['cmdline']}
    - {role: git, tags: ['git']}
    - {role: lynx, tags: ['lynx']}
    - {role: imgcat, tags: ['imgcat']}
    - {role: ruby, tags: ['ruby']}
    - {role: nvim, tags: ['nvim']}
    - {role: node, tags: ['node']}
    - {role: vscodium, tags: ['vscodium']}
    - {role: macos, tags: ['macos'], when: ansible_os_family == "Darwin"}
    - {role: development, tags: ['development']}

