---
- name: Install Firefox
  homebrew_cask:
    name: firefox
    state: present
    install_options: 'force,appdir=/Applications'
    sudo_password: "{{ mac_admin_pass }}"
    update_homebrew: yes
  when: ansible_os_family == "Darwin"
- name: Install Slack
  homebrew_cask:
    name: slack
    state: present
    install_options: 'force,appdir=/Applications'
    sudo_password: "{{ mac_admin_pass }}"
    update_homebrew: yes
  when: ansible_os_family == "Darwin"
# - name: Install Zoom
#   become: yes
#   homebrew_cask:
#     name: zoom
#     state: present
#     install_options: 'force,appdir=/Applications'
#     sudo_password: "{{ mac_admin_pass }}"
#     update_homebrew: yes
#   when: ansible_os_family == "Darwin"
- name: Install iTerm2
  homebrew_cask:
    name: iterm2
    state: present
    update_homebrew: yes
  when: ansible_os_family == "Darwin"
- name: Install Dash
  homebrew_cask:
    name: dash
    state: present
    install_options: 'force,appdir=/Applications'
    sudo_password: "{{ mac_admin_pass }}"
    update_homebrew: yes
  when: ansible_os_family == "Darwin"
- name: Install VSCodium
  homebrew_cask:
    name: vscodium
    state: present
    install_options: 'force,appdir=/Applications'
    sudo_password: "{{ mac_admin_pass }}"
    update_homebrew: yes
  when: ansible_os_family == "Darwin"
- name: Install keycastr
  homebrew_cask:
    name: keycastr
    state: present
    install_options: 'force,appdir=/Applications'
    sudo_password: "{{ mac_admin_pass }}"
    update_homebrew: yes
  when: ansible_os_family == "Darwin"
- name: Install bestres
  homebrew_cask:
    name: bestres
    state: present
    install_options: 'force,appdir=/Applications'
    sudo_password: "{{ mac_admin_pass }}"
    update_homebrew: yes
  when: ansible_os_family == "Darwin"
- name: Install devutils
  homebrew_cask:
    name: devutils
    state: present
    install_options: 'force,appdir=/Applications'
    sudo_password: "{{ mac_admin_pass }}"
    update_homebrew: yes
  when: ansible_os_family == "Darwin"
