---
- name: configure vscode
  template:
    src: settings.json.j2
    dest: "~/Library/Application\ Support/VSCodium/User/settings.json"
    owner: "{{ ansible_user_id }}"
    mode: 0644
- name: configure vscode marketplace
  template:
    src: product.json.j2
    dest: "~/Library/Application\ Support/VSCodium/product.json"
    owner: "{{ ansible_user_id }}"
    mode: 0644
