---
# - debug: var=hostvars['local']['git_client_email']
# - debug: var=hostvars['local']['git_client_name']
- name: Install Git
  homebrew:
    name: git
    state: present
- name: configure git client
  template:
    src: gitconfig.j2
    dest: "~/.gitconfig"
    owner: "{{ ansible_user_id }}"
    mode: 0644
