---
- name: create .config directory
  ansible.builtin.file:
    path: ~/.config
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: 0755
- name: configure startship toml
  template:
    src: starship.toml.j2
    dest: "~/.config/starship.toml"
    owner: "{{ ansible_user_id }}"
    mode: 0644
